version: "3"
services:
	prisma:
		image: prismagraphql/prisma:1.34
		restart: always
		ports:
			- "4467:4467"
		environment:
			PRISMA_CONFIG: |
				port: 4467
				databases:
					default:
						connector: mysql
						host: mysql
						port: 3306
						user: root
						password: prisma
	mysql:
		image: mysql:5.7
		restart: always
		ports:
			- "3308:3306"
		environment:
			MYSQL_ROOT_PASSWORD: prisma
		volumes:
			- mysql:/var/lib/mysql
		
volumes:
	mysql: ~
